// Generated by CoffeeScript 1.4.0
(function() {

  require.config({
    paths: {
      jquery: "lib/jquery-1.8.3",
      goog: "/_ah/channel/jsapi?",
      backbone: "lib/backbone",
      underscore: "lib/underscore",
      paper: "lib/paper"
    },
    shim: {
      goog: {
        exports: "goog"
      },
      paper: {
        exports: "paper"
      },
      underscore: {
        exports: "_"
      }
    }
  });

  require(["canvas", "path", "flyer", "paper", "underscore", "randpath"], function(Canvas, Path, Flyer, paper, _, RandPath) {
    var Point, canvas, down, flyer, freq, left, path, right, up;
    left = 0;
    right = 1000;
    freq = 3;
    path = new RandPath(left, right, 2, -2, freq, 0.1);
    flyer = new Flyer(path);
    canvas = new Canvas('game', path, [flyer]);
    console.log(path, canvas);
    Point = paper.Point;
    Path = paper.Path;
    canvas.view.setOnFrame(function(e) {
      flyer.go(1 / 30);
      if (flyer.pos.x > path.end) {
        flyer.pos.x = path.start;
      }
      return canvas.draw();
    });
    Point = paper.Point;
    down = function() {
      return flyer.acc = new Point(0, 5);
    };
    up = function() {
      return flyer.acc = new Point(0, 1);
    };
    $(window).mousedown(down);
    $(window).mouseup(up);
    $(window).on('touchstart', down);
    $(window).on('touchend', up);
    return window.path = path;
  });

}).call(this);
