// Generated by CoffeeScript 1.4.0
(function() {

  require.config({
    paths: {
      jquery: "lib/jquery-1.8.3",
      goog: "/_ah/channel/jsapi?",
      backbone: "lib/backbone",
      underscore: "lib/underscore",
      paper: "lib/paper"
    },
    shim: {
      goog: {
        exports: "goog"
      },
      paper: {
        exports: "paper"
      },
      underscore: {
        exports: "_"
      }
    }
  });

  require(["canvas", "path", "flyer", "paper"], function(Canvas, Path, Flyer, paper) {
    var Point, canvas, flyer, path;
    path = new Path(Math.sin, Math.cos, Math.PI / 2, Math.PI * 20 + Math.PI / 2, 0.1);
    flyer = new Flyer(path);
    canvas = new Canvas('game', path, [flyer]);
    console.log(path, canvas);
    canvas.view.setOnFrame(function() {
      flyer.go(1 / 30);
      if (flyer.pos.x > Math.PI * 20 + Math.PI / 2) {
        flyer.pos.x = Math.PI / 2;
      }
      return canvas.draw();
    });
    Point = paper.Point;
    $(window).mousedown(function() {
      flyer.acc = new Point(0, -5);
      return console.log(flyer.acc);
    });
    return $(window).mouseup(function() {
      flyer.acc = new Point(0, -1);
      return console.log(flyer.acc);
    });
  });

}).call(this);
