// Generated by CoffeeScript 1.4.0
(function() {

  require.config({
    paths: {
      jquery: "lib/jquery-1.8.3",
      goog: "/_ah/channel/jsapi?",
      backbone: "lib/backbone",
      underscore: "lib/underscore",
      paper: "lib/paper"
    },
    shim: {
      goog: {
        exports: "goog"
      },
      paper: {
        exports: "paper"
      },
      underscore: {
        exports: "_"
      }
    }
  });

  require(["canvas", "path", "flyer", "paper", "underscore", "randpath"], function(Canvas, Path, Flyer, paper, _, RandPath) {
    var Point, canvas, down, flyer, flyerPath, freq, left, path, right, up;
    left = 0;
    right = 1000;
    freq = 3;
    path = new RandPath(left, right, 2, -2, freq, 0.1);
    flyer = new Flyer(path);
    canvas = new Canvas('game', path, [flyer]);
    console.log(path, canvas);
    Point = paper.Point;
    Path = paper.Path;
    flyerPath = new Path();
    flyerPath.strokeColor = 'green';
    flyerPath.strokeWidth = 0.02;
    flyerPath.dashArray = [0.2, 0.1];
    canvas.view.setOnFrame(function(e) {
      var b, flyerFunc, flyerPathPoints, x;
      flyer.go(1 / 30);
      if (flyer.pos.x > path.end) {
        flyer.pos.x = path.start;
      }
      flyerFunc = flyer.getFunc().func;
      b = paper.view.getBounds();
      flyerPathPoints = (function() {
        var _i, _len, _ref, _results;
        _ref = _.range(flyer.pos.x, b.x + b.width, 0.1);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          x = _ref[_i];
          _results.push(new Point(x, flyerFunc(x)));
        }
        return _results;
      })();
      flyerPath.removeSegments();
      flyerPath.addSegments(flyerPathPoints);
      return canvas.draw();
    });
    Point = paper.Point;
    down = function() {
      return flyer.acc = new Point(0, 5);
    };
    up = function() {
      return flyer.acc = new Point(0, 1);
    };
    $(window).mousedown(down);
    $(window).mouseup(up);
    $(window).on('touchstart', down);
    $(window).on('touchend', up);
    return window.path = path;
  });

}).call(this);
