// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["paper", "underscore"], function(paper, _) {
    var FuncPath, Path, Point;
    Point = paper.Point;
    Path = (function() {

      function Path(at, grad, start, end, step) {
        this.at = at;
        this.grad = grad;
        this.start = start;
        this.end = end;
        this.step = step;
      }

      Path.prototype.getPoints = function() {
        var x, _i, _len, _ref, _results;
        _ref = _.range(this.start, this.end + this.step, this.step);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          x = _ref[_i];
          _results.push(new Point(x, this.at(x)));
        }
        return _results;
      };

      return Path;

    })();
    return FuncPath = (function(_super) {

      __extends(FuncPath, _super);

      function FuncPath(func, gradFunc, start, end, step) {
        var at, grad;
        this.func = func;
        this.gradFunc = gradFunc;
        at = function(x) {
          return new Point(x, this.func(x));
        };
        grad = function(x) {
          return new Point(1, this.gradFunc(x)).normalize();
        };
        FuncPath.__super__.constructor.call(this, at, grad, start, end, step);
      }

      FuncPath.prototype.getPoints = function() {
        var x, _i, _len, _ref, _results;
        _ref = _.range(this.start, this.end + this.step, this.step);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          x = _ref[_i];
          _results.push(this.at(x));
        }
        return _results;
      };

      return FuncPath;

    })(Path);
  });

}).call(this);
